export const GOT_GAMES_SUCCESSFULLY = "GOT_GAMES_SUCCESSFULLY";
export const ERROR_GETTING_GAMES = "ERROR_GETTING_GAMES";



export const SEARCH_RESULT = "SEARCH_RESULT";
export const FILTER_RESULT = "FILTER_RESULT";